-- Views generated from DDL in SCALER/view
-- Each view returns only rows with CURRENT_FLAG = 1
-- Columns are explicitly listed and comments copied from DDL
-- Schema: OWNBT_ODS

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCBP_V" AS
SELECT
	"OTSCBP_ID",
	"OTSCBP_BUSINESS_PARTNER_ID",
	"OTSCBP_BUSINESS_PARTNER_SAP_ID",
	"OTSCBP_BUSINESS_PARTNER_SAP_NAME",
	"OTSCBP_SYSTEM_ID",
	"OTSCBP_CREATED_DATE",
	"OTSCBP_CREATED_PROCESS",
	"OTSCBP_MODIFIED_DATE",
	"OTSCBP_MODIFIED_PROCESS",
	"OTSCBP_VALID_FROM",
	"OTSCBP_VALID_TO",
	"OTSCBP_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCBP"
WHERE "OTSCBP_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCBP_V" IS 'MKK SCALER - Tabulka pro data o obchodních partnerech. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_BUSINESS_PARTNER_ID" IS 'Unikátní identifikátor obchodního partnera v rámci datového skladu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_BUSINESS_PARTNER_SAP_ID" IS 'Primární identifikátor obchodního partnera v systému SAP.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_BUSINESS_PARTNER_SAP_NAME" IS 'Jméno obchodního partnera v systému SAP (KPJM).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_SYSTEM_ID" IS 'Identifikátor zdrojového systému, ze kterého data pochází.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_CREATED_DATE" IS 'Datum vytvoření záznamu v datovém skladu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCBP_V"."OTSCBP_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCDH_V" AS
SELECT
	"OTSCDH_ID",
	"OTSCDH_DOCUMENT_HISTORY_ID",
	"OTSCDH_DOCUMENT_ID",
	"OTSCDH_STATUS_ID",
	"OTSCDH_EVENT_DATETIME",
	"OTSCDH_EVENT_MESSAGE",
	"OTSCDH_JOB_ID",
	"OTSCDH_CREATED_DATE",
	"OTSCDH_CREATED_PROCESS",
	"OTSCDH_MODIFIED_DATE",
	"OTSCDH_MODIFIED_PROCESS",
	"OTSCDH_VALID_FROM",
	"OTSCDH_VALID_TO",
	"OTSCDH_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCDH"
WHERE "OTSCDH_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCDH_V" IS 'Tabulka historie stavů dokumentů. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_DOCUMENT_HISTORY_ID" IS 'Automaticky generované ID záznamu historie dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_DOCUMENT_ID" IS 'ID dokumentu, ke kterému se historie vztahuje.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_STATUS_ID" IS 'ID stavu dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_EVENT_DATETIME" IS 'Datum a čas události změny stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_EVENT_MESSAGE" IS 'Popis události nebo zpráva spojená se změnou stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_JOB_ID" IS 'ID úlohy, která provedla změnu stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDH_V"."OTSCDH_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCDO_V" AS
SELECT
		s."OTSCDO_ID",
		s."OTSCDO_DOCUMENT_ID",
		s."OTSCDO_PAGES_COUNT",
		s."OTSCDO_SHEET_COUNT",
		s."OTSCDO_SYSTEM_ID",
		s."OTSCDO_SYSTEM_NAME",
		s."OTSCDO_EXT_DOCUMENT_ID",
		s."OTSCDO_OUTPUT_CHANNEL",
		s."OTSCDO_DELIVERY_METHOD",
		s."OTSCDO_DOCUMENT_TYPE",
		oc."OCSTMP_TXTF" AS "OTSCDO_DOCUMENT_TYPE_TXT",
		s."OTSCDO_UCETNI_OKRUH",
		s."OTSCDO_BONM",
		s."OTSCDO_BOID",
		s."OTSCDO_SPLIT_KEY",
		s."OTSCDO_JOIN_KEY",
		s."OTSCDO_CREATED_DATETIME",
		s."OTSCDO_SMS_NUMBER",
		s."OTSCDO_EMAIL_FROM",
		s."OTSCDO_EMAIL_TO",
		s."OTSCDO_EMAIL_SUBJECT",
		s."OTSCDO_JOB_ID",
		s."OTSCDO_BUSINESS_PARTNER",
		s."OTSCDO_REFERENCE_NUM",
		s."OTSCDO_CREATED_DATE",
		s."OTSCDO_CREATED_PROCESS",
		s."OTSCDO_MODIFIED_DATE",
		s."OTSCDO_MODIFIED_PROCESS",
		s."OTSCDO_VALID_FROM",
		s."OTSCDO_VALID_TO",
		s."OTSCDO_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCDO" s
LEFT JOIN "OWNBT_ODS"."ODC_MDM_STMP" oc
	ON oc."OCSTMP_VALOBJ" = s."OTSCDO_DOCUMENT_TYPE"
WHERE s."OTSCDO_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCDO_V" IS 'Tabulka pro import dokumentů. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_DOCUMENT_ID" IS 'Identifikátor dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_PAGES_COUNT" IS 'Počet stran dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_SHEET_COUNT" IS 'Počet listů v dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_SYSTEM_ID" IS 'Identifikátor systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_SYSTEM_NAME" IS 'Název systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_EXT_DOCUMENT_ID" IS 'INTerní identifikátor dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_OUTPUT_CHANNEL" IS 'Výstupní kanál (např. email, tisk).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_DELIVERY_METHOD" IS 'Metoda doručení.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_DOCUMENT_TYPE" IS 'Typ dokumentu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_DOCUMENT_TYPE_TXT" IS 'Popis typu dokumentu (číselník OCSTMP, OCSTMP_TXTF).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_UCETNI_OKRUH" IS 'Účetní okruh.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_BONM" IS 'BONM.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_BOID" IS 'BOID.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_SPLIT_KEY" IS 'Klíč pro rozdělení.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_JOIN_KEY" IS 'Spojovací klíč.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_CREATED_DATETIME" IS 'Datum a čas vytvoření.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_SMS_NUMBER" IS 'Telefonní číslo pro SMS.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_EMAIL_FROM" IS 'Email odesílatele.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_EMAIL_TO" IS 'Email příjemce.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_EMAIL_SUBJECT" IS 'Předmět emailu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_JOB_ID" IS 'Identifikátor úlohy.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_BUSINESS_PARTNER" IS 'Identifikátor obchodního partnera.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_REFERENCE_NUM" IS 'Referenční číslo.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCDO_V"."OTSCDO_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCEH_V" AS
SELECT
	"OTSCEH_ID",
	"OTSCEH_ENVELOPE_HISTORY_ID",
	"OTSCEH_ENVELOPE_ID",
	"OTSCEH_STATUS_ID",
	"OTSCEH_EVENT_DATETIME",
	"OTSCEH_EVENT_MESSAGE",
	"OTSCEH_EXT_STATUS_NAME",
	"OTSCEH_EXT_STATUS_MESSAGE",
	"OTSCEH_SMTP_CODE",
	"OTSCEH_JOB_ID",
	"OTSCEH_CREATED_DATE",
	"OTSCEH_CREATED_PROCESS",
	"OTSCEH_MODIFIED_DATE",
	"OTSCEH_MODIFIED_PROCESS",
	"OTSCEH_VALID_FROM",
	"OTSCEH_VALID_TO",
	"OTSCEH_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCEH"
WHERE "OTSCEH_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCEH_V" IS 'Tabulka historie obálek. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_ENVELOPE_HISTORY_ID" IS 'Automaticky generované ID záznamu historie obálky.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_ENVELOPE_ID" IS 'ID obálky, ke které se historie vztahuje.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_STATUS_ID" IS 'ID stavu obálky.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_EVENT_DATETIME" IS 'Datum a čas události změny stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_EVENT_MESSAGE" IS 'Popis události nebo zpráva spojená se změnou stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_EXT_STATUS_NAME" IS 'INTerní název stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_EXT_STATUS_MESSAGE" IS 'INTerní popis stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_SMTP_CODE" IS 'SMTP kód chyby (pro email).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_JOB_ID" IS 'ID úlohy, která provedla změnu stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEH_V"."OTSCEH_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCEN_V" AS
SELECT
	"OTSCEN_ID",
	"OTSCEN_ENVELOPE_ID",
	"OTSCEN_REFERENCE_NUMBER",
	"OTSCEN_CREATED_DATE",
	"OTSCEN_CREATED_PROCESS",
	"OTSCEN_MODIFIED_DATE",
	"OTSCEN_MODIFIED_PROCESS",
	"OTSCEN_VALID_FROM",
	"OTSCEN_VALID_TO",
	"OTSCEN_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCEN"
WHERE "OTSCEN_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCEN_V" IS 'Tabulka pro obálky (envelopes). (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_ENVELOPE_ID" IS 'Identifikátor obálky.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_REFERENCE_NUMBER" IS 'Referenční číslo obálky.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCEN_V"."OTSCEN_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCPA_V" AS
SELECT
	"OTSCPA_ID",
	"OTSCPA_PSPPACKAGEID",
	"OTSCPA_PSPPACKAGECODE",
	"OTSCPA_PSPPACKAGENAME",
	"OTSCPA_PSPPACKAGEDESC",
	"OTSCPA_SYSTEMID",
	"OTSCPA_SYSTEMNAME",
	"OTSCPA_PSPATTACHMENTID",
	"OTSCPA_PSPATTACHMENTCODE",
	"OTSCPA_PSPATTACHMENTNAME",
	"OTSCPA_PSPATTACHMENTWEIGHT",
	"OTSCPA_PSPATTACHMENTDESC",
	"OTSCPA_PSPENVELOPETYPEID",
	"OTSCPA_PSPENVELOPETYPECODE",
	"OTSCPA_PSPENVELOPETYPEPRINT",
	"OTSCPA_PSPENVELOPETYPEDESC",
	"OTSCPA_PSPENVELOPETYPESIZE",
	"OTSCPA_CREATED_DATE",
	"OTSCPA_CREATED_PROCESS",
	"OTSCPA_MODIFIED_DATE",
	"OTSCPA_MODIFIED_PROCESS",
	"OTSCPA_VALID_FROM",
	"OTSCPA_VALID_TO",
	"OTSCPA_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCPA"
WHERE "OTSCPA_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCPA_V" IS 'Tabulka pro balíčky, přílohy a typy obálek. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPPACKAGEID" IS 'ID balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPPACKAGECODE" IS 'Kód balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPPACKAGENAME" IS 'Název balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPPACKAGEDESC" IS 'Popis balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_SYSTEMID" IS 'ID systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_SYSTEMNAME" IS 'Název systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPATTACHMENTID" IS 'ID přílohy balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPATTACHMENTCODE" IS 'Kód přílohy balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPATTACHMENTNAME" IS 'Název přílohy balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPATTACHMENTWEIGHT" IS 'Váha přílohy balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPATTACHMENTDESC" IS 'Popis přílohy balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPENVELOPETYPEID" IS 'ID typu obálky balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPENVELOPETYPECODE" IS 'Kód typu obálky balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPENVELOPETYPEPRINT" IS 'Indikátor tisku typu obálky.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPENVELOPETYPEDESC" IS 'Popis typu obálky balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_PSPENVELOPETYPESIZE" IS 'Velikost typu obálky balíčku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCPA_V"."OTSCPA_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCRQ_V" AS
SELECT
	"OTSCRQ_ID",
	"OTSCRQ_REQUEST_ID",
	"OTSCRQ_EXT_REQUEST_ID",
	"OTSCRQ_REQUEST_TYPE",
	"OTSCRQ_TEST",
	"OTSCRQ_REQUEST_USER",
	"OTSCRQ_SYSTEM_ID",
	"OTSCRQ_SYSTEM_NAME",
	"OTSCRQ_FINALIZED_DATETIME",
	"OTSCRQ_CREATED_DATETIME",
	"OTSCRQ_CREATED_DATE",
	"OTSCRQ_CREATED_PROCESS",
	"OTSCRQ_MODIFIED_DATE",
	"OTSCRQ_MODIFIED_PROCESS",
	"OTSCRQ_VALID_FROM",
	"OTSCRQ_VALID_TO",
	"OTSCRQ_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCRQ"
WHERE "OTSCRQ_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCRQ_V" IS 'Tabulka pro požadavky (requests). (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_REQUEST_ID" IS 'Automaticky generované ID požadavku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_EXT_REQUEST_ID" IS 'INTerní ID požadavku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_REQUEST_TYPE" IS 'Typ požadavku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_TEST" IS 'Indikátor testovacího požadavku (1=ano, 0=ne).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_REQUEST_USER" IS 'Uživatel, který požadavek vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_SYSTEM_ID" IS 'ID systému, ze kterého požadavek přišel.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_SYSTEM_NAME" IS 'Název systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_FINALIZED_DATETIME" IS 'Datum a čas dokončení požadavku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_CREATED_DATETIME" IS 'Datum a čas vytvoření požadavku.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCRQ_V"."OTSCRQ_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

CREATE OR REPLACE VIEW "OWNBT_ODS"."ODT_SCA_SCST_V" AS
SELECT
	"OTSCST_ID",
	"OTSCST_STATUS_ID",
	"OTSCST_STATUS_CODE",
	"OTSCST_ENTITY_NAME",
	"OTSCST_STATUS_NAME",
	"OTSCST_STATUS_DESCRIPTION_CZ",
	"OTSCST_STATUS_DESCRIPTION",
	"OTSCST_CREATED_DATE",
	"OTSCST_CREATED_PROCESS",
	"OTSCST_MODIFIED_DATE",
	"OTSCST_MODIFIED_PROCESS",
	"OTSCST_VALID_FROM",
	"OTSCST_VALID_TO",
	"OTSCST_CURRENT_FLAG"
FROM "OWNBT_ODS"."ODT_SCA_SCST"
WHERE "OTSCST_CURRENT_FLAG" = 1;

COMMENT ON TABLE "OWNBT_ODS"."ODT_SCA_SCST_V" IS 'Tabulka pro definici stavů. (view)';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_STATUS_ID" IS 'Automaticky generované ID stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_STATUS_CODE" IS 'Kód stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_ENTITY_NAME" IS 'Název entity, ke které se stav vztahuje (např. DOCUMENT, ENVELOPE).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_STATUS_NAME" IS 'Název stavu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_STATUS_DESCRIPTION_CZ" IS 'Popis stavu v češtině.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_STATUS_DESCRIPTION" IS 'Popis stavu v angličtině.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_CREATED_DATE" IS 'Datum vytvoření záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_CREATED_PROCESS" IS 'Název procesu, který záznam vytvořil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_MODIFIED_PROCESS" IS 'Identifikátor procesu, který záznam naposledy upravil.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_VALID_FROM" IS 'Datum začátku platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_VALID_TO" IS 'Datum konce platnosti záznamu (YYYYMMDD).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_SCA_SCST_V"."OTSCST_CURRENT_FLAG" IS 'Indikátor platnosti záznamu (1 = platný, 0 = historický).';

-- End of generated views with explicit columns and comments
