-- ...existing code...
--------------------------------------------------------
--  DDL for Table INT_FLX_FCDE
--------------------------------------------------------

  CREATE TABLE "OWNBT_INT"."INT_FLX_FCDE" 
   (	
    "ITFCDE_EFFECTIVE_DATE" NUMBER(8,0) NOT NULL ENABLE, 
    "ITFCDE_ID" NUMBER NOT NULL ENABLE, 
  "ITFCDE_COMMUNICATION_ID" VARCHAR2(20 CHAR), 
  "ITFCDE_DEVICE_ID_CRM" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "ITFCDE_SUPPLY_POINT_ID" NUMBER, 
  "ITFCDE_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
  "ITFCDE_PRODUCER" VARCHAR2(255 CHAR), 
  "ITFCDE_SERIAL_NUMBER" VARCHAR2(255 CHAR), 
  "ITFCDE_MODEL" VARCHAR2(255 CHAR), 
  "ITFCDE_VALID_FROM_UTC" TIMESTAMP (7), 
  "ITFCDE_VALID_TO_UTC" TIMESTAMP (7), 
  "ITFCDE_STATE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
  "ITFCDE_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "ITFCDE_MAX_OVERFLOW" NUMBER, 
    "ITFCDE_ONLINE" NUMBER, 
    "ITFCDE_MANAGEMENT_ENABLED" NUMBER, 
  "ITFCDE_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7), 
  "ITFCDE_LAST_MESSAGE_AT_UTC" TIMESTAMP (7), 
  "ITFCDE_CREATED_AT_UTC" TIMESTAMP (7), 
  "ITFCDE_UPDATED_AT_UTC" TIMESTAMP (7), 
  "ITFCDE_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
  "ITFCDE_SAP_VALID_FROM_UTC" TIMESTAMP (7), 
  "ITFCDE_SAP_VALID_TO_UTC" TIMESTAMP (7), 
    "ITFCDE_DELETED" NUMBER NOT NULL ENABLE, 
  "ITFCDE_CONTROL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "ITFCDE_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "ITFCDE_OUTFLOW_CONTROL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "ITFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
    "ITFCDE_CREATED_DATE" DATE, 
  "ITFCDE_CREATED_PROCESS" VARCHAR2(100 CHAR)
   ) 
PARTITION BY RANGE ("ITFCDE_EFFECTIVE_DATE")
INTERVAL (1)
(PARTITION p0 VALUES LESS THAN (20100000));

   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_DEVICE_ID_CRM" IS 'ID zařízení v systému CRM.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_SUPPLY_POINT_ID" IS 'ID připojeného odběrného místa.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_TYPE" IS 'Typ zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_PRODUCER" IS 'Výrobce zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_SERIAL_NUMBER" IS 'Sériové číslo zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_MODEL" IS 'Model zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_STATE" IS 'Technický stav zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_STATUS" IS 'Obchodní status zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_MAX_OVERFLOW" IS 'Maximální povolený přetok.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_ONLINE" IS 'Indikátor, zda je zařízení online (1/0).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno vzdálené řízení (1/0).';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace se zařízením.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_LAST_MESSAGE_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_SAP_VALID_FROM_UTC" IS 'Datum platnosti od v rámci SAP (pro časovou řadu).';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_SAP_VALID_TO_UTC" IS 'Datum platnosti do v rámci SAP (pro časovou řadu).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_CONTROL_STATUS" IS 'Stav řízení (ovládání) zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_OUTFLOW_CONTROL_STATUS" IS 'Stav řízení odtoku.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení odtoku.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FCDE"."ITFCDE_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "OWNBT_INT"."INT_FLX_FCDE"  IS 'Záznamy o centrálních zařízeních (Central Devices) a jejich stavu.';


  CREATE TABLE "OWNBT_INT"."INT_FLX_FDEV" 
   (	
    "ITFDEV_EFFECTIVE_DATE" NUMBER(8,0) NOT NULL ENABLE, 
    "ITFDEV_ID" NUMBER NOT NULL ENABLE, 
  "ITFDEV_COMMUNICATION_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE,
  "ITFDEV_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "ITFDEV_LAST_MESSAGE_AT_UTC" TIMESTAMP (7),
  "ITFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "ITFDEV_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7),
  "ITFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "ITFDEV_OVERALL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE,
  "ITFDEV_OVERALL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "ITFDEV_COMMUNICATION_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "ITFDEV_COMMUNICATION_STATUS_CHANGED_UTC" TIMESTAMP (7), 
    "ITFDEV_CREATED_DATE" DATE, 
  "ITFDEV_CREATED_PROCESS" VARCHAR2(100 CHAR)
   ) 
PARTITION BY RANGE ("ITFDEV_EFFECTIVE_DATE")
INTERVAL (1)
(PARTITION p0 VALUES LESS THAN (20100000));

   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_TYPE" IS 'Typ zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_LAST_MESSAGE_AT_UTC" IS 'Čas vytvoření poslední zprávy zařízením.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace (odeslání) se zařízením.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" IS 'Čas poslední komunikace (příjem) se zařízením.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_OVERALL_STATUS" IS 'Celkový souhrnný status zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_OVERALL_STATUS_CHANGED_UTC" IS 'Čas poslední změny celkového statusu.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_COMMUNICATION_STATUS" IS 'Status komunikace (dostupnosti) zařízení.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_COMMUNICATION_STATUS_CHANGED_UTC" IS 'Čas poslední změny statusu komunikace.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FDEV"."ITFDEV_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "OWNBT_INT"."INT_FLX_FDEV"  IS 'Záznamy o decentralizovaných zařízeních (Devices) a jejich stavu.';

--------------------------------------------------------
--  DDL for Table INT_FLX_FSPO
--------------------------------------------------------

  CREATE TABLE "OWNBT_INT"."INT_FLX_FSPO" 
   (	
    "ITFSPO_EFFECTIVE_DATE" NUMBER(8,0) NOT NULL ENABLE, 
    "ITFSPO_ID" NUMBER NOT NULL ENABLE, 
  "ITFSPO_ID_CRM" VARCHAR2(20 CHAR), 
    "ITFSPO_EAN" CHAR(13 CHAR), 
  "ITFSPO_VALID_FROM_UTC" TIMESTAMP (7), 
  "ITFSPO_VALID_TO_UTC" TIMESTAMP (7), 
  "ITFSPO_REGISTRATION_STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "ITFSPO_REGION_ID" NUMBER, 
    "ITFSPO_CONSUMPTION_TYPE_PROFILE_ID" NUMBER, 
    "ITFSPO_REGION_COVERAGE_PROFILE_ID" NUMBER, 
    "ITFSPO_REGION_PREDICTION_PROFILE_ID" NUMBER, 
    "ITFSPO_RESERVED_OUTPUT" NUMBER, 
    "ITFSPO_TELEMETRY_ENABLED" NUMBER, 
  "ITFSPO_TELEMETRY_ENABLED_AT_UTC" TIMESTAMP (7), 
  "ITFSPO_TELEMETRY_UPDATED_AT_UTC" TIMESTAMP (7), 
    "ITFSPO_CALCULATION_ENABLED" NUMBER, 
    "ITFSPO_MANAGEMENT_ENABLED" NUMBER, 
    "ITFSPO_MAX_LIMITED_ENERGY" NUMBER, 
    "ITFSPO_SPENT_LIMITED_ENERGY" NUMBER, 
    "ITFSPO_LIMITED_ENERGY" NUMBER, 
    "ITFSPO_POINTS" NUMBER NOT NULL ENABLE, 
  "ITFSPO_CREATED_AT_UTC" TIMESTAMP (7) NOT NULL ENABLE, 
  "ITFSPO_UPDATED_AT_UTC" TIMESTAMP (7) NOT NULL ENABLE, 
  "ITFSPO_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
    "ITFSPO_DELETED" NUMBER NOT NULL ENABLE, 
    "ITFSPO_APPLIED_RESERVED_OUTPUT" NUMBER, 
    "ITFSPO_CREATED_DATE" DATE, 
  "ITFSPO_CREATED_PROCESS" VARCHAR2(100 CHAR)
   )
PARTITION BY RANGE ("ITFSPO_EFFECTIVE_DATE")
INTERVAL (1)
(PARTITION p0 VALUES LESS THAN (20100000));

   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_ID" IS 'Primární klíč, unikátní identifikátor odběrného místa.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_ID_CRM" IS 'ID odběrného místa v systému CRM.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_EAN" IS 'Kód EAN odběrného místa.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_REGISTRATION_STATUS" IS 'Status registrace odběrného místa.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_REGION_ID" IS 'ID regionu.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_CONSUMPTION_TYPE_PROFILE_ID" IS 'ID profilu typu spotřeby.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_REGION_COVERAGE_PROFILE_ID" IS 'ID profilu pokrytí regionu.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_REGION_PREDICTION_PROFILE_ID" IS 'ID predikčního profilu regionu.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_RESERVED_OUTPUT" IS 'Rezervovaný výkon.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_TELEMETRY_ENABLED" IS 'Indikátor, zda je telemetrie povolena (1/0).';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_TELEMETRY_ENABLED_AT_UTC" IS 'Čas povolení telemetrie.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_TELEMETRY_UPDATED_AT_UTC" IS 'Čas poslední aktualizace telemetrických dat.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_CALCULATION_ENABLED" IS 'Indikátor, zda je povolen výpočet (1/0).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno řízení (1/0).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_MAX_LIMITED_ENERGY" IS 'Maximální limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_SPENT_LIMITED_ENERGY" IS 'Spotřebovaná limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_LIMITED_ENERGY" IS 'Aktuální limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_POINTS" IS 'Počet bodů (nebo tarifních položek).';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_APPLIED_RESERVED_OUTPUT" IS 'Aplikovaný rezervovaný výkon.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_INT"."INT_FLX_FSPO"."ITFSPO_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "OWNBT_INT"."INT_FLX_FSPO"  IS 'Záznamy o odběrných místech (Supply Points) a jejich parametrech.';

