  CREATE TABLE "OWNBT_ODS"."ODT_FLX_FCDE" 
   (	
    "OTFCDE_ID" NUMBER NOT NULL ENABLE, 
  "OTFCDE_COMMUNICATION_ID" VARCHAR2(20 CHAR), 
  "OTFCDE_DEVICE_ID_CRM" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "OTFCDE_SUPPLY_POINT_ID" NUMBER, 
  "OTFCDE_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
  "OTFCDE_PRODUCER" VARCHAR2(255 CHAR), 
  "OTFCDE_SERIAL_NUMBER" VARCHAR2(255 CHAR), 
  "OTFCDE_MODEL" VARCHAR2(255 CHAR), 
  "OTFCDE_VALID_FROM_UTC" TIMESTAMP (7), 
  "OTFCDE_VALID_TO_UTC" TIMESTAMP (7), 
  "OTFCDE_STATE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
  "OTFCDE_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "OTFCDE_MAX_OVERFLOW" NUMBER, 
    "OTFCDE_ONLINE" NUMBER, 
    "OTFCDE_MANAGEMENT_ENABLED" NUMBER, 
  "OTFCDE_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7), 
  "OTFCDE_LAST_MESSAGE_AT_UTC" TIMESTAMP (7), 
  "OTFCDE_CREATED_AT_UTC" TIMESTAMP (7), 
  "OTFCDE_UPDATED_AT_UTC" TIMESTAMP (7), 
  "OTFCDE_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
  "OTFCDE_SAP_VALID_FROM_UTC" TIMESTAMP (7), 
  "OTFCDE_SAP_VALID_TO_UTC" TIMESTAMP (7), 
    "OTFCDE_DELETED" NUMBER NOT NULL ENABLE, 
  "OTFCDE_CONTROL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "OTFCDE_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "OTFCDE_OUTFLOW_CONTROL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "OTFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
	"OTFCDE_CREATED_DATE" DATE, 
	"OTFCDE_CREATED_PROCESS" NUMBER, 
	"OTFCDE_MODIFIED_DATE" DATE, 
	"OTFCDE_MODIFIED_PROCESS" NUMBER, 
	"OTFCDE_VALID_FROM" NUMBER(8,0) NOT NULL ENABLE, 
	"OTFCDE_VALID_TO" NUMBER(8,0), 
	"OTFCDE_CURRENT_FLAG" NUMBER(1,0)
   ) 

ALTER TABLE "OWNBT_ODS"."ODT_FLX_FCDE"
ADD CONSTRAINT ODT_FLX_FCDE_PK
PRIMARY KEY ("OTFCDE_ID", "OTFCDE_VALID_FROM")
ENABLE;

   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_DEVICE_ID_CRM" IS 'ID zařízení v systému CRM.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_SUPPLY_POINT_ID" IS 'ID připojeného odběrného místa.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_TYPE" IS 'Typ zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_PRODUCER" IS 'Výrobce zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_SERIAL_NUMBER" IS 'Sériové číslo zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_MODEL" IS 'Model zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_STATE" IS 'Technický stav zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_STATUS" IS 'Obchodní status zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_MAX_OVERFLOW" IS 'Maximální povolený přetok.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_ONLINE" IS 'Indikátor, zda je zařízení online (1/0).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno vzdálené řízení (1/0).';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace se zařízením.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_LAST_MESSAGE_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_SAP_VALID_FROM_UTC" IS 'Datum platnosti od v rámci SAP (pro časovou řadu).';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_SAP_VALID_TO_UTC" IS 'Datum platnosti do v rámci SAP (pro časovou řadu).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CONTROL_STATUS" IS 'Stav řízení (ovládání) zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_OUTFLOW_CONTROL_STATUS" IS 'Stav řízení odtoku.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení odtoku.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu v systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_MODIFIED_PROCESS" IS 'Proces, který záznam naposledy modifikoval.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_VALID_FROM" IS 'Datum (ve formátu YYYYMMDD), od kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 start).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_VALID_TO" IS 'Datum (ve formátu YYYYMMDD), do kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 end).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FCDE"."OTFCDE_CURRENT_FLAG" IS 'Příznak (1/0), zda se jedná o aktuální platnou verzi záznamu (SCD Type 2 current flag).';
   COMMENT ON TABLE "OWNBT_ODS"."ODT_FLX_FCDE"  IS 'Záznamy o centrálních zařízeních (Control Devices) a jejich stavu.';


  CREATE TABLE "OWNBT_ODS"."ODT_FLX_FDEV" 
   (	
    "OTFDEV_ID" NUMBER NOT NULL ENABLE, 
  "OTFDEV_COMMUNICATION_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE,
  "OTFDEV_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "OTFDEV_LAST_MESSAGE_AT_UTC" TIMESTAMP (7),
  "OTFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "OTFDEV_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7),
  "OTFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "OTFDEV_OVERALL_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE,
  "OTFDEV_OVERALL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "OTFDEV_COMMUNICATION_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
  "OTFDEV_COMMUNICATION_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "OTFDEV_CREATED_DATE" DATE, 
	"OTFDEV_CREATED_PROCESS" NUMBER, 
	"OTFDEV_MODIFIED_DATE" DATE, 
	"OTFDEV_MODIFIED_PROCESS" NUMBER, 
	"OTFDEV_VALID_FROM" NUMBER(8,0) NOT NULL ENABLE, 
	"OTFDEV_VALID_TO" NUMBER(8,0), 
	"OTFDEV_CURRENT_FLAG" NUMBER(1,0)
   ) 

ALTER TABLE "OWNBT_ODS"."ODT_FLX_FDEV"
ADD CONSTRAINT ODT_FLX_FDEV_PK
PRIMARY KEY ("OTFDEV_ID", "OTFDEV_VALID_FROM")
ENABLE;

   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_TYPE" IS 'Typ zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_LAST_MESSAGE_AT_UTC" IS 'Čas vytvoření poslední zprávy zařízením.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace (odeslání) se zařízením.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" IS 'Čas poslední komunikace (příjem) se zařízením.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_OVERALL_STATUS" IS 'Celkový souhrnný status zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_OVERALL_STATUS_CHANGED_UTC" IS 'Čas poslední změny celkového statusu.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_COMMUNICATION_STATUS" IS 'Status komunikace (dostupnosti) zařízení.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_COMMUNICATION_STATUS_CHANGED_UTC" IS 'Čas poslední změny statusu komunikace.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_EFFECTIVE_DATE" IS 'Datum (ve formátu YYYYMMDD), od kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 start). (Sloupec pro partition).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu v systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_MODIFIED_PROCESS" IS 'Proces, který záznam naposledy modifikoval.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_VALID_FROM" IS 'Datum (ve formátu YYYYMMDD), od kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 start).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_VALID_TO" IS 'Datum (ve formátu YYYYMMDD), do kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 end).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FDEV"."OTFDEV_CURRENT_FLAG" IS 'Příznak (1/0), zda se jedná o aktuální platnou verzi záznamu (SCD Type 2 current flag).';
   COMMENT ON TABLE "OWNBT_ODS"."ODT_FLX_FDEV"  IS 'Záznamy o decentralizovaných zařízeních (Devices) a jejich stavu.';

--------------------------------------------------------
--  DDL for Table ODT_FLX_FSPO
--------------------------------------------------------

  CREATE TABLE "OWNBT_ODS"."ODT_FLX_FSPO" 
   (	
    "OTFSPO_ID" NUMBER NOT NULL ENABLE, 
  "OTFSPO_ID_CRM" VARCHAR2(20 CHAR), 
    "OTFSPO_EAN" CHAR(13 CHAR), 
  "OTFSPO_VALID_FROM_UTC" TIMESTAMP (7), 
  "OTFSPO_VALID_TO_UTC" TIMESTAMP (7), 
  "OTFSPO_REGISTRATION_STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
    "OTFSPO_REGION_ID" NUMBER, 
    "OTFSPO_CONSUMPTION_TYPE_PROFILE_ID" NUMBER, 
    "OTFSPO_REGION_COVERAGE_PROFILE_ID" NUMBER, 
    "OTFSPO_REGION_PREDICTION_PROFILE_ID" NUMBER, 
    "OTFSPO_RESERVED_OUTPUT" NUMBER, 
    "OTFSPO_TELEMETRY_ENABLED" NUMBER, 
  "OTFSPO_TELEMETRY_ENABLED_AT_UTC" TIMESTAMP (7), 
  "OTFSPO_TELEMETRY_UPDATED_AT_UTC" TIMESTAMP (7), 
    "OTFSPO_CALCULATION_ENABLED" NUMBER, 
    "OTFSPO_MANAGEMENT_ENABLED" NUMBER, 
    "OTFSPO_MAX_LIMITED_ENERGY" NUMBER, 
    "OTFSPO_SPENT_LIMITED_ENERGY" NUMBER, 
    "OTFSPO_LIMITED_ENERGY" NUMBER, 
    "OTFSPO_POINTS" NUMBER NOT NULL ENABLE, 
  "OTFSPO_CREATED_AT_UTC" TIMESTAMP (7) NOT NULL ENABLE, 
  "OTFSPO_UPDATED_AT_UTC" TIMESTAMP (7) NOT NULL ENABLE, 
  "OTFSPO_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
    "OTFSPO_DELETED" NUMBER NOT NULL ENABLE, 
    "OTFSPO_APPLIED_RESERVED_OUTPUT" NUMBER, 
  "OTFSPO_CREATED_DATE" DATE, 
	"OTFSPO_CREATED_PROCESS" NUMBER, 
	"OTFSPO_MODIFIED_DATE" DATE, 
	"OTFSPO_MODIFIED_PROCESS" NUMBER, 
	"OTFSPO_VALID_FROM" NUMBER(8,0) NOT NULL ENABLE, 
	"OTFSPO_VALID_TO" NUMBER(8,0), 
	"OTFSPO_CURRENT_FLAG" NUMBER(1,0)
   )

ALTER TABLE "OWNBT_ODS"."ODT_FLX_FSPO"
ADD CONSTRAINT ODT_FLX_FSPO_PK
PRIMARY KEY ("OTFSPO_ID", "OTFSPO_VALID_FROM")
ENABLE;

   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_ID" IS 'Primární klíč, unikátní identifikátor odběrného místa.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_ID_CRM" IS 'ID odběrného místa v systému CRM.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_EAN" IS 'Kód EAN odběrného místa.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_REGISTRATION_STATUS" IS 'Status registrace odběrného místa.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_REGION_ID" IS 'ID regionu.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CONSUMPTION_TYPE_PROFILE_ID" IS 'ID profilu typu spotřeby.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_REGION_COVERAGE_PROFILE_ID" IS 'ID profilu pokrytí regionu.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_REGION_PREDICTION_PROFILE_ID" IS 'ID predikčního profilu regionu.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_RESERVED_OUTPUT" IS 'Rezervovaný výkon.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_TELEMETRY_ENABLED" IS 'Indikátor, zda je telemetrie povolena (1/0).';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_TELEMETRY_ENABLED_AT_UTC" IS 'Čas povolení telemetrie.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_TELEMETRY_UPDATED_AT_UTC" IS 'Čas poslední aktualizace telemetrických dat.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CALCULATION_ENABLED" IS 'Indikátor, zda je povolen výpočet (1/0).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno řízení (1/0).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_MAX_LIMITED_ENERGY" IS 'Maximální limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_SPENT_LIMITED_ENERGY" IS 'Spotřebovaná limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_LIMITED_ENERGY" IS 'Aktuální limitovaná energie.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_POINTS" IS 'Počet bodů (nebo tarifních položek).';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_APPLIED_RESERVED_OUTPUT" IS 'Aplikovaný rezervovaný výkon.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_EFFECTIVE_DATE" IS 'Datum (ve formátu YYYYMMDD), od kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 start). (Sloupec pro partition).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_MODIFIED_DATE" IS 'Datum poslední modifikace záznamu v systému.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_MODIFIED_PROCESS" IS 'Proces, který záznam naposledy modifikoval.';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_VALID_FROM" IS 'Datum (ve formátu YYYYMMDD), od kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 start).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_VALID_TO" IS 'Datum (ve formátu YYYYMMDD), do kterého je verze záznamu platná z pohledu datového skladu (SCD Type 2 end).';
COMMENT ON COLUMN "OWNBT_ODS"."ODT_FLX_FSPO"."OTFSPO_CURRENT_FLAG" IS 'Příznak (1/0), zda se jedná o aktuální platnou verzi záznamu (SCD Type 2 current flag).';
   COMMENT ON TABLE "OWNBT_ODS"."ODT_FLX_FSPO"  IS 'Záznamy o odběrných místech (Supply Points) a jejich parametrech.';

