-- ...existing code...
--------------------------------------------------------
--  DDL for Table FLXT_FCDE
--------------------------------------------------------

  CREATE TABLE "EXT_IMPORT"."FLXT_FCDE" 
   (	"XTFCDE_ID" NUMBER, 
    "XTFCDE_COMMUNICATION_ID" VARCHAR2(500 CHAR), 
    "XTFCDE_DEVICE_ID_CRM" VARCHAR2(500 CHAR), 
    "XTFCDE_SUPPLY_POINT_ID" NUMBER, 
    "XTFCDE_TYPE" VARCHAR2(500 CHAR), 
    "XTFCDE_PRODUCER" VARCHAR2(500 CHAR), 
    "XTFCDE_SERIAL_NUMBER" VARCHAR2(500 CHAR), 
    "XTFCDE_MODEL" VARCHAR2(500 CHAR), 
  "XTFCDE_VALID_FROM_UTC" TIMESTAMP (7), 
  "XTFCDE_VALID_TO_UTC" TIMESTAMP (7), 
    "XTFCDE_STATE" VARCHAR2(500 CHAR), 
    "XTFCDE_STATUS" VARCHAR2(500 CHAR), 
    "XTFCDE_MAX_OVERFLOW" NUMBER, 
    "XTFCDE_ONLINE" NUMBER, 
    "XTFCDE_MANAGEMENT_ENABLED" NUMBER, 
  "XTFCDE_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7), 
  "XTFCDE_LAST_MESSAGE_AT_UTC" TIMESTAMP (7), 
  "XTFCDE_CREATED_AT_UTC" TIMESTAMP (7), 
  "XTFCDE_UPDATED_AT_UTC" TIMESTAMP (7), 
  "XTFCDE_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
  "XTFCDE_SAP_VALID_FROM_UTC" TIMESTAMP (7), 
  "XTFCDE_SAP_VALID_TO_UTC" TIMESTAMP (7), 
    "XTFCDE_DELETED" NUMBER, 
    "XTFCDE_CONTROL_STATUS" VARCHAR2(500 CHAR), 
  "XTFCDE_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "XTFCDE_OUTFLOW_CONTROL_STATUS" VARCHAR2(500 CHAR), 
  "XTFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
    "XTFCDE_CREATED_DATE" DATE, 
    "XTFCDE_CREATED_PROCESS" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXT_IMPORT_TS" ;

   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_DEVICE_ID_CRM" IS 'ID zařízení v systému CRM.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_SUPPLY_POINT_ID" IS 'ID připojeného odběrného místa.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_TYPE" IS 'Typ zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_PRODUCER" IS 'Výrobce zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_SERIAL_NUMBER" IS 'Sériové číslo zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_MODEL" IS 'Model zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_STATE" IS 'Technický stav zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_STATUS" IS 'Obchodní status zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_MAX_OVERFLOW" IS 'Maximální povolený přetok.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_ONLINE" IS 'Indikátor, zda je zařízení online (1/0).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno vzdálené řízení (1/0).';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace se zařízením.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_LAST_MESSAGE_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_SAP_VALID_FROM_UTC" IS 'Datum platnosti od v rámci SAP (pro časovou řadu).';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_SAP_VALID_TO_UTC" IS 'Datum platnosti do v rámci SAP (pro časovou řadu).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_CONTROL_STATUS" IS 'Stav řízení (ovládání) zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_OUTFLOW_CONTROL_STATUS" IS 'Stav řízení odtoku.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_OUTFLOW_CONTROL_STATUS_CHANGED_UTC" IS 'Čas poslední změny stavu řízení odtoku.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FCDE"."XTFCDE_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "EXT_IMPORT"."FLXT_FCDE"  IS 'Záznamy o centrálních zařízeních (Central Devices) a jejich stavu.';
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FCDE" TO "ETL_PROVOZ";
  GRANT ALTER ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";
  GRANT DELETE ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";
  GRANT INDEX ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";
  GRANT INSERT ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";
  GRANT UPDATE ON "EXT_IMPORT"."FLXT_FCDE" TO "OWNER_ETL";

  CREATE TABLE "EXT_IMPORT"."FLXT_FDEV" 
   (	"XTFDEV_ID" NUMBER, 
    "XTFDEV_COMMUNICATION_ID" VARCHAR2(500 CHAR),
    "XTFDEV_TYPE" VARCHAR2(500 CHAR), 
  "XTFDEV_LAST_MESSAGE_AT_UTC" TIMESTAMP (7),
  "XTFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "XTFDEV_LAST_COMMUNICATION_AT_UTC" TIMESTAMP (7),
  "XTFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" TIMESTAMP (7), 
  "XTFDEV_OVERALL_STATUS" VARCHAR2(500 CHAR), 
  "XTFDEV_OVERALL_STATUS_CHANGED_UTC" TIMESTAMP (7), 
  "XTFDEV_COMMUNICATION_STATUS" VARCHAR2(500 CHAR), 
  "XTFDEV_COMMUNICATION_STATUS_CHANGED_UTC" TIMESTAMP (7), 
    "XTFDEV_CREATED_DATE" DATE, 
    "XTFDEV_CREATED_PROCESS" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXT_IMPORT_TS" ;



   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_ID" IS 'Primární klíč, unikátní identifikátor zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_COMMUNICATION_ID" IS 'Komunikační ID zařízení.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_TYPE" IS 'Typ zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_LAST_MESSAGE_AT_UTC" IS 'Čas vytvoření poslední zprávy zařízením.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_LAST_MESSAGE_RECEIVED_AT_UTC" IS 'Čas přijetí poslední zprávy ze zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_LAST_COMMUNICATION_AT_UTC" IS 'Čas poslední komunikace (odeslání) se zařízením.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_LAST_COMMUNICATION_RECEIVED_AT_UTC" IS 'Čas poslední komunikace (příjem) se zařízením.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_OVERALL_STATUS" IS 'Celkový souhrnný status zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_OVERALL_STATUS_CHANGED_UTC" IS 'Čas poslední změny celkového statusu.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_COMMUNICATION_STATUS" IS 'Status komunikace (dostupnosti) zařízení.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_COMMUNICATION_STATUS_CHANGED_UTC" IS 'Čas poslední změny statusu komunikace.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FDEV"."XTFDEV_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "EXT_IMPORT"."FLXT_FDEV"  IS 'Záznamy o decentralizovaných zařízeních (Devices) a jejich stavu.';
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FDEV" TO "ETL_PROVOZ";
  GRANT ALTER ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
  GRANT DELETE ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
  GRANT INDEX ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
  GRANT INSERT ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
  GRANT UPDATE ON "EXT_IMPORT"."FLXT_FDEV" TO "OWNER_ETL";
--------------------------------------------------------
--  DDL for Table FLXT_FSPO
--------------------------------------------------------

  CREATE TABLE "EXT_IMPORT"."FLXT_FSPO" 
   (	"XTFSPO_ID" NUMBER, 
    "XTFSPO_ID_CRM" VARCHAR2(500 CHAR), 
    "XTFSPO_EAN" CHAR(13 CHAR), 
  "XTFSPO_VALID_FROM_UTC" TIMESTAMP (7), 
  "XTFSPO_VALID_TO_UTC" TIMESTAMP (7), 
    "XTFSPO_REGISTRATION_STATUS" VARCHAR2(500 CHAR), 
    "XTFSPO_REGION_ID" NUMBER, 
    "XTFSPO_CONSUMPTION_TYPE_PROFILE_ID" NUMBER, 
    "XTFSPO_REGION_COVERAGE_PROFILE_ID" NUMBER, 
    "XTFSPO_REGION_PREDICTION_PROFILE_ID" NUMBER, 
    "XTFSPO_RESERVED_OUTPUT" NUMBER, 
    "XTFSPO_TELEMETRY_ENABLED" NUMBER, 
  "XTFSPO_TELEMETRY_ENABLED_AT_UTC" TIMESTAMP (7), 
  "XTFSPO_TELEMETRY_UPDATED_AT_UTC" TIMESTAMP (7), 
    "XTFSPO_CALCULATION_ENABLED" NUMBER, 
    "XTFSPO_MANAGEMENT_ENABLED" NUMBER, 
    "XTFSPO_MAX_LIMITED_ENERGY" NUMBER, 
    "XTFSPO_SPENT_LIMITED_ENERGY" NUMBER, 
    "XTFSPO_LIMITED_ENERGY" NUMBER, 
    "XTFSPO_POINTS" NUMBER, 
  "XTFSPO_CREATED_AT_UTC" TIMESTAMP (7), 
  "XTFSPO_UPDATED_AT_UTC" TIMESTAMP (7), 
  "XTFSPO_SAP_SYNCED_AT_UTC" TIMESTAMP (7), 
    "XTFSPO_DELETED" NUMBER, 
    "XTFSPO_APPLIED_RESERVED_OUTPUT" NUMBER, 
    "XTFSPO_CREATED_DATE" DATE, 
    "XTFSPO_CREATED_PROCESS" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXT_IMPORT_TS" ;

   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_ID" IS 'Primární klíč, unikátní identifikátor odběrného místa.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_ID_CRM" IS 'ID odběrného místa v systému CRM.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_EAN" IS 'Kód EAN odběrného místa.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_VALID_FROM_UTC" IS 'Datum a čas, od kdy je záznam platný.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_VALID_TO_UTC" IS 'Datum a čas, do kdy je záznam platný.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_REGISTRATION_STATUS" IS 'Status registrace odběrného místa.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_REGION_ID" IS 'ID regionu.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_CONSUMPTION_TYPE_PROFILE_ID" IS 'ID profilu typu spotřeby.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_REGION_COVERAGE_PROFILE_ID" IS 'ID profilu pokrytí regionu.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_REGION_PREDICTION_PROFILE_ID" IS 'ID predikčního profilu regionu.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_RESERVED_OUTPUT" IS 'Rezervovaný výkon.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_TELEMETRY_ENABLED" IS 'Indikátor, zda je telemetrie povolena (1/0).';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_TELEMETRY_ENABLED_AT_UTC" IS 'Čas povolení telemetrie.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_TELEMETRY_UPDATED_AT_UTC" IS 'Čas poslední aktualizace telemetrických dat.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_CALCULATION_ENABLED" IS 'Indikátor, zda je povolen výpočet (1/0).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_MANAGEMENT_ENABLED" IS 'Indikátor, zda je povoleno řízení (1/0).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_MAX_LIMITED_ENERGY" IS 'Maximální limitovaná energie.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_SPENT_LIMITED_ENERGY" IS 'Spotřebovaná limitovaná energie.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_LIMITED_ENERGY" IS 'Aktuální limitovaná energie.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_POINTS" IS 'Počet bodů (nebo tarifních položek).';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_CREATED_AT_UTC" IS 'Čas vytvoření záznamu.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_UPDATED_AT_UTC" IS 'Čas poslední aktualizace záznamu.';
  COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_SAP_SYNCED_AT_UTC" IS 'Čas poslední synchronizace do SAP.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_DELETED" IS 'Indikátor smazání záznamu (1/0).';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_APPLIED_RESERVED_OUTPUT" IS 'Aplikovaný rezervovaný výkon.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_CREATED_DATE" IS 'Datum vytvoření záznamu v systému.';
   COMMENT ON COLUMN "EXT_IMPORT"."FLXT_FSPO"."XTFSPO_CREATED_PROCESS" IS 'Proces, který záznam vytvořil.';
   COMMENT ON TABLE "EXT_IMPORT"."FLXT_FSPO"  IS 'Záznamy o odběrných místech (Supply Points) a jejich parametrech.';
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FSPO" TO "ETL_PROVOZ";
  GRANT ALTER ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
  GRANT DELETE ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
  GRANT INDEX ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
  GRANT INSERT ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
  GRANT SELECT ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
  GRANT UPDATE ON "EXT_IMPORT"."FLXT_FSPO" TO "OWNER_ETL";
